# -*- coding: utf-8 -*-
"""nlp_pipeline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wSpR20jNYEfoJ_WSjkIE-0R1vWDnN5Xt
"""

import pandas as pd
import matplotlib.pyplot as plt

import spacy

nlp = spacy.blank("en")

corp = nlp("To address this dilemma, lots of research endeavor have investigated init to facilitate the discovery of novel PPIs. Among these methods, PPI prediction techniques that merely rely on proteinsequence data are more widespread than other methods which require extensive biological domain knowledge")

for token in corp:
  print(token)

nlp1 = spacy.load("en_core_web_sm")
nlp1.pipe_names

corp1 = nlp1("To address this dilemma, lots of research endeavor have investigated init to facilitate the discovery of novel PPIs. Among these methods, PPI prediction techniques that merely rely on proteinsequence data are more widespread than other methods which require extensive biological domain knowledge")
for token in corp1:
  print(token, " | ", token.pos_, " | ", token.lemma_ )

nlp.add_pipe("lemmatizer" , source=nlp1)
nlp.pipe_names

corp = nlp("To address this dilemma, lots of research endeavor have investigated init to facilitate the discovery of novel PPIs. Among these methods, PPI prediction techniques that merely rely on proteinsequence data are more widespread than other methods which require extensive biological domain knowledge")
for token in corp:
    print(token, " | ", token.pos_, " | ", token.lemma_ )

import nltk
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

corp2=["In this paper"," we propose a multi-modal", "deep representation", "learning" ,"structure by" ,"incorporating", "protein physicochemical features with the graph topological features from the PPI networks"]

for word in corp2:
  print(word, " | ", stemmer.stem(word))

#customizing

customizer = nlp1.get_pipe('attribute_ruler')
customizer.add([[{"TEXT":"deep"}],[{"TEXT":"representation"}]],{"LEMMA":"DR"})
corp3 = nlp1("In this paper, we propose a multi-modal deep representation learning structure by incorporating protein physicochemical features with the graph topological features from the PPI networks")

for token in corp3:
  print(token, " | ", token.lemma_)